name: 'Run Sonar'
description: 'Run SonarQube analysis with Maven'
inputs:
  projectBaseDir:
    description: 'Base directory of the project'
    required: false
    default: '.'
  sonarHostUrl:
    description: 'SonarQube server URL'
    required: true
  sonarToken:
    description: 'SonarQube authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Test
      run: echo "Valeu"
      shell: bash
      
    - name: Run SonarQube analysis
      run: mvn sonar:sonar -Dsonar.host.url=${{ inputs.sonarHostUrl }} -Dsonar.login=${{ inputs.sonarToken }} -Dsonar.projectBaseDir=${{ inputs.projectBaseDir }}
      shell: bash
